filetype plugin indent on
syntax on

colorscheme jellybeans

set guifont="DejaVu Monospace 6"

set guioptions-=T
set guioptions-=m
set guioptions-=L
set guioptions-=r
set guioptions-=e
set guioptions+=c
