filetype plugin indent on
syntax on

colorscheme jellybeans
set guioptions-=T
set guioptions-=m
set guioptions-=L
set guioptions-=r
set guioptions-=e
set guioptions+=c

set columns=110
set lines=65

set guifont=Monospace\ 9
