execute pathogen#infect()
execute pathogen#helptags()

filetype plugin indent on
syntax on

set directory=~/.vim/swap

colorscheme jellybeans
set number              " display line numbers
set cursorline          " highlight the current line
set hlsearch            " set highlight search on
set scrolloff=4         " Keep cursor 4 lines away form window edges
set shiftwidth=4        " operation >> indents 4 columns; << unindents 4 columns
set tabstop=4           " a hard TAB displays as 4 columns
set expandtab           " insert spaces then hitting TABs
set softtabstop=4       " insert/delete 4 spaces when hitting TAB/BACKSPACE
set shiftround          " round indent to multiple of 'shiftwidth'
set autoindent          " align the new line indent with the previous line
set smartindent
set wildmode=longest,list,full      " sensible tab-completion behavior
set wildmenu                        " extend tab-completion with interactive menu
set laststatus=2
set nocompatible

" Remove trailing whitespaces when writing a buffer to file
autocmd BufWritePre * :%s/\s\+$//ge

" Use Markdown syntax highlighting for .md-files
autocmd BufNewFile,BufRead *.md set syntax=markdown

" Remap leader to hyphen
let mapleader = "-"

" A more handy Esc
inoremap kj <Esc>

" Jumpt to start and end of line using home row keys
noremap H ^
noremap L $

" Cycle through tabs like in firefox
map <C-n> :tabn<CR>
map <C-p> :tabp<CR>

" New from practical vim

" Testing
nnoremap <silent> åb :bprevious<CR>

nnoremap <silent> <C-l> :<C-u>nohlsearch<CR><C-l>

set incsearch

" Vim-Fugitive

set statusline=%<%f\ %h%m%r%{fugitive#statusline()}%=%-14.(%l,%c%V%)\ %P

" PythonMode

let g:pymode_rope_complete_on_dot = 0
let g:pymode_rope = 0
let g:pymode_options_max_line_length = 79
let g:pymode_options_colorcolumn = 0
let g:pymode_folding = 0

" vim-airline

let g:airline#extensions#tabline#enabled = 1
let g:airline_theme='jellybeans'
