execute pathogen#infect()
execute pathogen#helptags()

set nocompatible
filetype plugin indent on
syntax on


set shiftround                  " round indent to multiple of 'shiftwidth'
set shiftwidth=4                " operation >> indents 4 columns; << unindents 4 columns
set softtabstop=4               " insert/delete 4 spaces when hitting TAB/BACKSPACE
set tabstop=4                   " a hard TAB displays as 4 columns
set autoindent                  " align the new line indent with the previous line
set cindent
set expandtab                   " insert spaces then hitting TABs

set hlsearch                    " hightlight matches
set incsearch                   " seach as characters are entered

set number                      " display line numbers
set cursorline                  " highlight the current line
set showcmd                     " show command in bottom bar
set scrolloff=4                 " Keep cursor 4 lines away form window edges

set directory=~/.vim/swap
set laststatus=2
set ttyfast
set lazyredraw                  " redraw only when we need to
set path+=**
set wildmenu                    " extend tab-completion with interactive menu
set wildmode=longest,list,full  " sensible tab-completion behavior

set foldenable                  " enable folding
set foldlevelstart=10           " open most folds by default
set foldnestmax=10
set foldmethod=indent           " fold based on indent level

set report=0


" Auto commands ==============================================================

" Remove trailing whitespaces when writing a buffer to file
autocmd BufWritePre * :%s/\s\+$//ge

" Use Markdown syntax highlighting for .md-files
autocmd BufNewFile,BufRead *.md set syntax=markdown

autocmd ColorScheme * highlight StatusLine ctermbg=darkgray ctermfg=white cterm=NONE

" Key bindings ===============================================================

let mapleader = ","

" space open/closes folds
nnoremap <space> za

" move vertically by visual line
nnoremap j gj
nnoremap k gk

" kj is escape
inoremap kj <Esc>

" move to beginning/end of line
noremap H ^
noremap L $

" Cycle through tabs like in firefox
map <C-n> :tabn<CR>
map <C-p> :tabp<CR>

nnoremap <silent> <C-l> :<C-u>nohlsearch<CR><C-l>

" Netrw ======================================================================

let g:netrw_banner=0
let g:netrw_altv=1
let g:netrw_liststyle=3

" Python mode plugin =========================================================

let g:pymode_rope_complete_on_dot = 0
let g:pymode_rope = 0
let g:pymode_options_max_line_length = 79
let g:pymode_options_colorcolumn = 0
let g:pymode_folding = 0

colorscheme jellybeans
